server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb # Default local uri

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://auth-mongo:27017/authdb}
